#!/bin/bash
clear
if [ "$ganti" == "$(cat /data/lcn | grep -w "$ganti" | cut -d: -f1|sed 's/ //g')" ]
then
akitiftekan="$(cat /data/lcn | grep -w "$ganti" | cut -d: -f2|sed 's/ //g')"
maxinstall="$(cat /data/lcn | grep -w "$ganti" | cut -d: -f3|sed 's/ //g')"
olehinstall="$(cat /data/lcn | grep -w "$ganti" | cut -d: -f4|sed 's/ //g')"
olehinstall2="$(($(cat /data/lcn | grep -w "$ganti" | cut -d: -f4|sed 's/ //g')-1))"
sed -i "s|$ganti      :$aktiftekan      : $maxinstall      : $olehinstall |$ganti      :$aktiftekan      : $maxinstall      : $olehinstall2 |g"
else
clear
echo -e "$ganti Tidak Terdaftar"
fi
